apiVersion : apps/v1
kind: Deployment
metadata:
  name: "appweu-6044"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "appweu-6044"
  template:
    metadata:
      labels:
        app: "appweu-6044"
    spec:
      containers:
        - name: "appweu-6044"
          image: "saulweu.azurecr.io/appweu"
          ports:
          - containerPort: 3000