apiVersion: v1
kind: Service
metadata:
    name: "appweu-6044"
    labels:
        app: "appweu-6044"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "appweu-6044"